// src/lib/brand-designs.ts - Design Templates Only (Content Generated by AI)
export interface BrandDesign {
  name: string;
  colors: { primary: string; gradient: string; accent: string };
  stats: Array<{ value: string; label: string }>;
  layout: 'centered' | 'split' | 'minimal';
}

const BRAND_DESIGNS: Record<string, BrandDesign> = {
  uber: {
    name: "Uber Eats",
    colors: { primary: "#FF6B35", gradient: "linear-gradient(135deg, #FF6B35 0%, #FDBA74 100%)", accent: "#F97316" },
    stats: [
      { value: "10M+", label: "Daily Orders" },
      { value: "30min", label: "Avg Delivery" },
      { value: "4.9★", label: "App Rating" }
    ],
    layout: 'centered'
  },

  doordash: {
    name: "DoorDash",
    colors: { primary: "#FF3008", gradient: "linear-gradient(135deg, #FF3008 0%, #FF8A80 100%)", accent: "#FF5722" },
    stats: [
      { value: "500K+", label: "Restaurants" },
      { value: "2M+", label: "Daily Orders" },
      { value: "$5B+", label: "Payouts" }
    ],
    layout: 'split'
  },

  astar: {
    name: "A-Star Limousine",
    colors: { primary: "#1E3A8A", gradient: "linear-gradient(135deg, #1E3A8A 0%, #60A5FA 100%)", accent: "#2563EB" },
    stats: [
      { value: "500+", label: "5★ Events" },
      { value: "24/7", label: "Service" },
      { value: "100%", label: "On-Time" }
    ],
    layout: 'centered'
  },

  default: {
    name: "Your Brand",
    colors: { primary: "#3B82F6", gradient: "linear-gradient(135deg, #3B82F6 0%, #8B5CF6 100%)", accent: "#1D4ED8" },
    stats: [
      { value: "10K+", label: "Happy Customers" },
      { value: "24/7", label: "Support" },
      { value: "4.9★", label: "Rating" }
    ],
    layout: 'centered'
  }
};

export function getBrandDesign(url: string, detectedBrand?: string): BrandDesign {
  const hostname = url.toLowerCase();
  const brandText = detectedBrand?.toLowerCase() || '';

  // Check URL first
  if (hostname.includes('uber') || hostname.includes('ubereats')) {
    return BRAND_DESIGNS.uber;
  }
  if (hostname.includes('doordash')) {
    return BRAND_DESIGNS.doordash;
  }
  if (hostname.includes('astar') || hostname.includes('limousine') || hostname.includes('chauffeur')) {
    return BRAND_DESIGNS.astar;
  }

  // Check detected brand text
  if (brandText.includes('uber') || brandText.includes('eats')) {
    return BRAND_DESIGNS.uber;
  }
  if (brandText.includes('doordash') || brandText.includes('dash')) {
    return BRAND_DESIGNS.doordash;
  }
  if (brandText.includes('astar') || brandText.includes('limousine') || brandText.includes('chauffeur') || brandText.includes('luxury')) {
    return BRAND_DESIGNS.astar;
  }

  return BRAND_DESIGNS.default;
}